### ISSUE TITLE
Alarm every 48 hours

### ISSUE THREAD

**Issue by silveredbadger** [LendaDeAfonselio/Alarm_Bot#29]
how can I set an alarm every other day?

**Comment by LendaDeAfonselio** [comment]
Hello,
This is a very tricky question because it can be done with the current commands of the bot, but it's not very intuitive...

This is what I mean by that:
Running an alarm every other day is the same as saying that, in a month you wish to run an alarm on odd or even days.

Here is the command to set up an alarm in every even day of every month at 9AM:
`$alarm 0 9 */2 * * <your_message>`

Here is the command to set up an alarm in every odd day of every month at 9AM:
`$alarm 0 0 1-31/2 * * <your_message>`

Therefore if you wish to have a alarm for every two days every single month of the year you would have two options:

1. Every month set up the alarm you desire and delete the old one, the new alarm would depend on where the "old alarm" was last activated, if in the penultimate day of the month you would need to set up the alarm for odd days, otherwise for even: ```$deleteAlarm <id_old> 
 $alarm 0 9 */2 * * <your_message> or $alarm 0 0 1-31/2 * * <your_message>```
2. Create two alarms that express the specific pattern for each month, i.e something like this (say that the first alarm you would want is on the 1st of January):
``` $alarm 0 9 */2 2,3,5,8,11,12 * <your_message> 
$alarm 0 0 1-31/2 1,4,6,7,9,10 * <your_message>
```

Sorry about the lenghty response and feel free to hit me up on discord (Afonselio#5546) should you wish to discuss more about this subject.


[Source](https://community.splunk.com/t5/Archive/Cronjob-for-48-hours/m-p/317491)
